service: serverless-mail-service

plugins:
  - '@cruglobal/serverless-merge-config'
  - serverless-webpack
  - serverless-offline
  - serverless-pseudo-parameters

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: sa-east-1
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  iamRoleStatements:
    - ${file(iam/EmailsTableIAM.yml):EmailsTableIAM}
  environment:
    EMAILS_TABLE_NAME: ${self:custom.EmailsTable.name}
    $<<: ${file(.env.yml)}

resources:
  Resources:
    EmailsTable: ${file(resources/EmailsTable.yml):EmailsTable}

functions:
  sendEmail:
    handler: src/handler.sendEmail
    timeout: 30
    events:
      - http: 
          path: send-email
          method: post

custom:
  EmailsTable:
    name: !Ref EmailsTable
    arn: !GetAtt EmailsTable.Arn
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

package:
  exclude:
    - .env.*
